version: 1

update_configs:

  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
        dependency_name: "@types/*"
      - match:
        dependency_name: "*eslint*"
      - match:
        dependency_name: "*jest*"
      # NOTE: electron and electron-builder in devDependencies required
      # - match:
      #     dependency_type: development
      #     update_type: all
