version: 1

update_configs:

  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "@types/*"
      - match:
          dependency_name: "*eslint*"
      - match:
          dependency_name: "*jest*"
      - match:
          dependency_name: "*prettier*"
      - match:
          dependency_name: "*testing-library*"
      - match:
          update_type: "semver:patch"
          # "security:patch"
          # "semver:minor"
          # "in_range"
          # "all"
