name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get-version
        run: echo "::set-output name=node::$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-version.outputs.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get-version
        run: echo "::set-output name=node::$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-version.outputs.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Type
        run: npm run type

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get-version
        run: echo "::set-output name=node::$(cat .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-version.outputs.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
